server:
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://database-6.cbph6zdnic3x.ap-northeast-2.rds.amazonaws.com:3306/bridge
    username: admin
    password: kdata4321!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
# ===================================================================
# Swagger Open-API options
# ===================================================================
springdoc:
  api-docs:
    enabled: true
    #path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    default-models-expand-depth: -1 # set to -1 completely hide the section "Schema"
    filter: true

#bucket name for get images from AWS S3 file storage
aws:
  bucket: makesense-s
